<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="42" ignored="0" total="46" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Logo" duration-ms="99854" started-at="2019-09-06T09:50:22Z" finished-at="2019-09-06T09:52:02Z">
    <groups>
    </groups>
    <test name="Logo" duration-ms="99854" started-at="2019-09-06T09:50:22Z" finished-at="2019-09-06T09:52:02Z">
      <class name="Logo">
        <test-method status="PASS" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3228" started-at="2019-09-06T09:50:23Z" data-provider="data" finished-at="2019-09-06T09:50:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[efectycolombia]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Payvalida/Efecty, folder=Efecty, shortcode=efectycolombia}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2969" started-at="2019-09-06T09:50:26Z" data-provider="data" finished-at="2019-09-06T09:50:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[pse]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Payvalida/PSE, folder=PSE, shortcode=pse}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2428" started-at="2019-09-06T09:50:29Z" data-provider="data" finished-at="2019-09-06T09:50:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[boletobancario]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Ebanx, folder=Boleto, shortcode=boletobancario}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="PASS" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2098" started-at="2019-09-06T09:50:31Z" data-provider="data" finished-at="2019-09-06T09:50:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[santandermexico]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Astropay/Santander Mexico, folder=Santander, shortcode=santandermexico}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2271" started-at="2019-09-06T09:50:33Z" data-provider="data" finished-at="2019-09-06T09:50:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[oxxo]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Astropay/OXXO, folder=OXXO, shortcode=oxxo}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2479" started-at="2019-09-06T09:50:36Z" data-provider="data" finished-at="2019-09-06T09:50:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ccbrazil]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Ebanx CC, folder=Ebanx\\Ebanx (Visa,Mastercard only), shortcode=ccbrazil}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NAME] expected [name] but found [ps-ebanx-d@2x],
[NAME] expected [name] but found [ps-ebanx-@2x],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NAME] expected [name] but found [ps-ebanx-d@2x],
[NAME] expected [name] but found [ps-ebanx-@2x],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2305" started-at="2019-09-06T09:50:38Z" data-provider="data" finished-at="2019-09-06T09:50:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ccbrazilhipercard]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Ebanx CC Hipercard, folder=Hiperbank, shortcode=ccbrazilhipercard}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="1818" started-at="2019-09-06T09:50:40Z" data-provider="data" finished-at="2019-09-06T09:50:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[itaubrazil]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Ebanx/Banco Itau, folder=Itau, shortcode=itaubrazil}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="1862" started-at="2019-09-06T09:50:42Z" data-provider="data" finished-at="2019-09-06T09:50:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[bancobrazil]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Ebanx/Banco do Brazil, folder=Banco do Brazil, shortcode=bancobrazil}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="1962" started-at="2019-09-06T09:50:44Z" data-provider="data" finished-at="2019-09-06T09:50:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[banrisulbrazil]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Ebanx/Banco Banrisul, folder=Banrisul, shortcode=banrisulbrazil}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NAME] expected [name] but found [ps-banrisul-d@2x],
[NAME] expected [name] but found [ps-banrisul-@2x],
[NumberOfTypeImage] expected [9] but found [6]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NAME] expected [name] but found [ps-banrisul-d@2x],
[NAME] expected [name] but found [ps-banrisul-@2x],
[NumberOfTypeImage] expected [9] but found [6]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="PASS" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2055" started-at="2019-09-06T09:50:46Z" data-provider="data" finished-at="2019-09-06T09:50:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[efecty]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Astropay/Efecty, folder=Efecty, shortcode=efecty}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2592" started-at="2019-09-06T09:50:48Z" data-provider="data" finished-at="2019-09-06T09:50:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[dotpaymt]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Dotpay/mTransfer, folder=mBank, shortcode=dotpaymt}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2990" started-at="2019-09-06T09:50:51Z" data-provider="data" finished-at="2019-09-06T09:50:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[dotpaybzwbk]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Dotpay/Bank Zachodni WBK, folder=WBK, shortcode=dotpaybzwbk}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2961" started-at="2019-09-06T09:50:54Z" data-provider="data" finished-at="2019-09-06T09:50:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[dotpayingb]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Dotpay/ING Bank Slaski, folder=ING, shortcode=dotpayingb}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3131" started-at="2019-09-06T09:50:57Z" data-provider="data" finished-at="2019-09-06T09:51:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[dotpayinteligo]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Dotpay/Inteligo, folder=Inteligo, shortcode=dotpayinteligo}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2977" started-at="2019-09-06T09:51:00Z" data-provider="data" finished-at="2019-09-06T09:51:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[dotpayingbacc]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Dotpay/Place z ING Bank Slaski, folder=Dotpay Place z ING Bank Slaski, shortcode=dotpayingbacc}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2978" started-at="2019-09-06T09:51:03Z" data-provider="data" finished-at="2019-09-06T09:51:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[happyvoucher]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Payletter/Happy Voucher, folder=Happyvoucher, shortcode=happyvoucher}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="15" started-at="2019-09-06T09:51:06Z" data-provider="data" finished-at="2019-09-06T09:51:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[teencash]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Payletter/TeenCash, folder=Teencash, shortcode=teencash}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][0] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][0] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [0]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2420" started-at="2019-09-06T09:51:06Z" data-provider="data" finished-at="2019-09-06T09:51:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[oncash]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Payletter/OnCash, folder=Oncash, shortcode=oncash}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2029" started-at="2019-09-06T09:51:08Z" data-provider="data" finished-at="2019-09-06T09:51:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[eggmoney]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Payletter/Eggmoney, folder=Eggmoney, shortcode=eggmoney}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="4" started-at="2019-09-06T09:51:10Z" data-provider="data" finished-at="2019-09-06T09:51:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[culturevoucher]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Payletter/Culture Voucher, folder=Culture voucher, shortcode=culturevoucher}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][1] expected [true] but found [false],
[NAME] expected [name] but found [culture voucher_original],
[NumberOfTypeImage] expected [9] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][1] expected [true] but found [false],
[NAME] expected [name] but found [culture voucher_original],
[NumberOfTypeImage] expected [9] but found [0]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2718" started-at="2019-09-06T09:51:10Z" data-provider="data" finished-at="2019-09-06T09:51:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[allthegate]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Payletter/AllTheGate CC, folder=Payletter AlltheGate, shortcode=allthegate}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3101" started-at="2019-09-06T09:51:13Z" data-provider="data" finished-at="2019-09-06T09:51:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[bookculture]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Payletter/Book Gift Voucher, folder=BookGiftVoucher, shortcode=bookculture}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NAME] expected [name] but found [book voucher v5],
[NAME] expected [name] but found [book voucher v7],
[NAME] expected [name] but found [book voucher_original],
[NumberOfTypeImage] expected [9] but found [8],
[multi][Height] expected [43] but found [44],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NAME] expected [name] but found [book voucher v5],
[NAME] expected [name] but found [book voucher v7],
[NAME] expected [name] but found [book voucher_original],
[NumberOfTypeImage] expected [9] but found [8],
[multi][Height] expected [43] but found [44],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2953" started-at="2019-09-06T09:51:16Z" data-provider="data" finished-at="2019-09-06T09:51:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[idealpayments]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=PPRO/iDeal, folder=PPRO IDEAL, shortcode=idealpayments}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3374" started-at="2019-09-06T09:51:19Z" data-provider="data" finished-at="2019-09-06T09:51:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[gameon]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Game-ON, folder=Game On, shortcode=gameon}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3030" started-at="2019-09-06T09:51:22Z" data-provider="data" finished-at="2019-09-06T09:51:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[culturevoucherkr]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Culture Voucher, folder=Culture land, shortcode=culturevoucherkr}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="13" started-at="2019-09-06T09:51:26Z" data-provider="data" finished-at="2019-09-06T09:51:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[teencashkr]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Teencash, folder=Teencash, shortcode=teencashkr}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][0] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][0] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [0]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3083" started-at="2019-09-06T09:51:26Z" data-provider="data" finished-at="2019-09-06T09:51:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[banktransfercn]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Umpay bank transfer, folder=Umpay, shortcode=banktransfercn}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3055" started-at="2019-09-06T09:51:29Z" data-provider="data" finished-at="2019-09-06T09:51:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[boletobr]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=MercadoPago/Boleto, folder=Boleto, shortcode=boletobr}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3017" started-at="2019-09-06T09:51:32Z" data-provider="data" finished-at="2019-09-06T09:51:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[idealnl]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Mollie/Ideal, folder=Ideal, shortcode=idealnl}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3114" started-at="2019-09-06T09:51:35Z" data-provider="data" finished-at="2019-09-06T09:51:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[yandexmoney]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Yandex/Yandex Money, folder=Yandex, shortcode=yandexmoney}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3055" started-at="2019-09-06T09:51:38Z" data-provider="data" finished-at="2019-09-06T09:51:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[sberbankonline]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Yandex/Sberbank Online, folder=Sberbank, shortcode=sberbankonline}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3005" started-at="2019-09-06T09:51:41Z" data-provider="data" finished-at="2019-09-06T09:51:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[alfaclickya]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Yandex/Alfa Click, folder=AlfaBank, shortcode=alfaclickya}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3055" started-at="2019-09-06T09:51:44Z" data-provider="data" finished-at="2019-09-06T09:51:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[tinkoff]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Yandex/Tinkoff, folder=Tinkoff, shortcode=tinkoff}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3060" started-at="2019-09-06T09:51:47Z" data-provider="data" finished-at="2019-09-06T09:51:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[yacash]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Yandex/Cash, folder=YandexCash, shortcode=yacash}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3137" started-at="2019-09-06T09:51:50Z" data-provider="data" finished-at="2019-09-06T09:51:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[walmart]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Openbucks/Walmart, folder=Walmart moneygram, shortcode=walmart}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3036" started-at="2019-09-06T09:51:53Z" data-provider="data" finished-at="2019-09-06T09:51:56Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[moneygram]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Openbucks/MoneyGram, folder=Moneygram, shortcode=moneygram}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][6] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [6],
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2944" started-at="2019-09-06T09:51:56Z" data-provider="data" finished-at="2019-09-06T09:51:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[canadapost]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Openbucks/Canada Post, folder=Canadapost, shortcode=canadapost}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[ImageNotFound] expected [] but found [dark2],
[ImageNotFound] expected [] but found [dark3],
[ImageNotFound] expected [] but found [light3],
[ImageNotFound] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="8" started-at="2019-09-06T09:51:59Z" data-provider="data" finished-at="2019-09-06T09:51:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[banktransferth]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Megapay / Bank transfer Thailand, folder=, shortcode=banktransferth}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][0] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][0] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [0]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="12" started-at="2019-09-06T09:51:59Z" data-provider="data" finished-at="2019-09-06T09:51:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[gateway]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Gateway, folder=Gateway, shortcode=gateway}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][0] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][0] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [0]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="PASS" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2327" started-at="2019-09-06T09:51:59Z" data-provider="data" finished-at="2019-09-06T09:52:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[gateway]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Gateway - AMEX only, folder=AMEX, shortcode=gateway}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="4" started-at="2019-09-06T09:52:02Z" data-provider="data" finished-at="2019-09-06T09:52:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[epspayments]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=PPRO/EPS, folder=, shortcode=epspayments}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][0] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][0] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [0]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3" started-at="2019-09-06T09:52:02Z" data-provider="data" finished-at="2019-09-06T09:52:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mol]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=zGold-MOLPoints, folder=, shortcode=mol}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][0] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][0] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [0]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3" started-at="2019-09-06T09:52:02Z" data-provider="data" finished-at="2019-09-06T09:52:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[multibanco]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=PPRO/Multibanco, folder=, shortcode=multibanco}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][0] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][0] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [0]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="4" started-at="2019-09-06T09:52:02Z" data-provider="data" finished-at="2019-09-06T09:52:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[epinpaymentsystem]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=MINT, folder=, shortcode=epinpaymentsystem}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][0] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][0] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [0]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3" started-at="2019-09-06T09:52:02Z" data-provider="data" finished-at="2019-09-06T09:52:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[cvspharmacy]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Openbucks/CVS Pharmacy, folder=, shortcode=cvspharmacy}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NumberImage][0] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NumberImage][0] expected [true] but found [false],
[NumberOfTypeImage] expected [9] but found [0]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:209)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
      </class> <!-- Logo -->
    </test> <!-- Logo -->
  </suite> <!-- Logo -->
</testng-results>
