<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="PW-HAN-063" name="automation.project3ds.oldTest.BrickURL_OFF1_Test" tests="24" failures="2" timestamp="19 Sep 2019 09:32:39 GMT" time="911.764" errors="1">
  <testcase name="execute" time="64.577" classname="automation.project3ds.oldTest.BrickURL_OFF1_Test"/>
  <testcase name="execute" time="70.819" classname="automation.project3ds.oldTest.BrickURL_OFF1_Test"/>
  <testcase name="execute" time="26.712" classname="automation.project3ds.oldTest.BrickURL_OFF1_Test"/>
  <testcase name="execute" time="49.424" classname="automation.project3ds.oldTest.BrickURL_OFF1_Test"/>
  <testcase name="execute" time="62.353" classname="automation.project3ds.oldTest.BrickURL_OFF1_Test"/>
  <testcase name="execute" time="36.030" classname="automation.project3ds.oldTest.BrickURL_OFF1_Test"/>
  <testcase name="execute" time="34.944" classname="automation.project3ds.oldTest.BrickURL_OFF1_Test"/>
  <testcase name="execute" time="31.512" classname="automation.project3ds.oldTest.BrickURL_OFF1_Test"/>
  <testcase name="execute" time="21.873" classname="automation.project3ds.oldTest.BrickURL_OFF1_Test"/>
  <testcase name="execute" time="34.848" classname="automation.project3ds.oldTest.BrickURL_OFF1_Test"/>
  <testcase name="execute" time="12.252" classname="automation.project3ds.oldTest.BrickURL_OFF1_Test">
    <error type="java.sql.SQLException" message="Illegal operation on empty result set.">
      <![CDATA[java.sql.SQLException: Illegal operation on empty result set.
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
at com.mysql.cj.jdbc.result.ResultSetImpl.checkRowPos(ResultSetImpl.java:497)
at com.mysql.cj.jdbc.result.ResultSetImpl.getString(ResultSetImpl.java:854)
at com.mysql.cj.jdbc.result.ResultSetImpl.getString(ResultSetImpl.java:872)
at automation.project3ds.Pslog.get_Fasterpay_payment_order_id(Pslog.java:77)
at automation.project3ds.oldTest.BrickURL_OFF1_Test.execute(BrickURL_OFF1_Test.java:87)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- execute -->
  <testcase name="execute" time="36.936" classname="automation.project3ds.oldTest.BrickURL_OFF1_Test">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	[Enrolled] expected [] but found [U]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
[Enrolled] expected [] but found [U]
at automation.project3ds.MySoftAssertAll.assertAll(MySoftAssertAll.java:57)
at automation.project3ds.Action.assertResultV1(Action.java:268)
at automation.project3ds.Action.assertResultV1(Action.java:156)
at automation.project3ds.oldTest.BrickURL_OFF1_Test.execute(BrickURL_OFF1_Test.java:93)
at sun.reflect.GeneratedMethodAccessor90.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- execute -->
  <testcase name="execute" time="33.314" classname="automation.project3ds.oldTest.BrickURL_OFF1_Test"/>
  <testcase name="execute" time="32.194" classname="automation.project3ds.oldTest.BrickURL_OFF1_Test">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	[Enrolled] expected [] but found [U]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
[Enrolled] expected [] but found [U]
at automation.project3ds.MySoftAssertAll.assertAll(MySoftAssertAll.java:57)
at automation.project3ds.Action.assertResultV1(Action.java:268)
at automation.project3ds.Action.assertResultV1(Action.java:156)
at automation.project3ds.oldTest.BrickURL_OFF1_Test.execute(BrickURL_OFF1_Test.java:93)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- execute -->
  <testcase name="execute" time="34.478" classname="automation.project3ds.oldTest.BrickURL_OFF1_Test"/>
  <testcase name="execute" time="50.157" classname="automation.project3ds.oldTest.BrickURL_OFF1_Test"/>
  <testcase name="execute" time="21.731" classname="automation.project3ds.oldTest.BrickURL_OFF1_Test"/>
  <testcase name="execute" time="47.983" classname="automation.project3ds.oldTest.BrickURL_OFF1_Test"/>
  <testcase name="execute" time="21.852" classname="automation.project3ds.oldTest.BrickURL_OFF1_Test"/>
  <testcase name="execute" time="40.237" classname="automation.project3ds.oldTest.BrickURL_OFF1_Test"/>
  <testcase name="execute" time="21.471" classname="automation.project3ds.oldTest.BrickURL_OFF1_Test"/>
  <testcase name="execute" time="31.360" classname="automation.project3ds.oldTest.BrickURL_OFF1_Test"/>
  <testcase name="execute" time="55.165" classname="automation.project3ds.oldTest.BrickURL_OFF1_Test"/>
  <testcase name="execute" time="39.542" classname="automation.project3ds.oldTest.BrickURL_OFF1_Test"/>
</testsuite> <!-- automation.project3ds.oldTest.BrickURL_OFF1_Test -->
