<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="PW-HAN-063" name="automation.project3ds.oldTest.BrickWidget_OFF1_Test" tests="25" failures="3" timestamp="16 Sep 2019 04:55:30 GMT" time="881.446" errors="0">
  <testcase name="execute" time="25.246" classname="automation.project3ds.oldTest.BrickWidget_OFF1_Test"/>
  <testcase name="execute" time="40.001" classname="automation.project3ds.oldTest.BrickWidget_OFF1_Test"/>
  <testcase name="execute" time="40.763" classname="automation.project3ds.oldTest.BrickWidget_OFF1_Test"/>
  <testcase name="execute" time="64.720" classname="automation.project3ds.oldTest.BrickWidget_OFF1_Test">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	[expected_results_authentication] expected [NA] but found [cmpi_authenticate response
PAResStatus = A
SignatureVerification = Y
EciFlag = 01
Xid = &lt;Xid Value&gt;
Cavv = &lt;Cavv Value&gt;
ErrorNo = 0
ErrorDesc = &lt;blank&gt;]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
[expected_results_authentication] expected [NA] but found [cmpi_authenticate response
PAResStatus = A
SignatureVerification = Y
EciFlag = 01
Xid = <Xid Value>
Cavv = <Cavv Value>
ErrorNo = 0
ErrorDesc = <blank>]
at automation.project3ds.MySoftAssertAll.assertAll(MySoftAssertAll.java:57)
at automation.project3ds.Action.assertResultV1(Action.java:268)
at automation.project3ds.Action.assertResultV1(Action.java:156)
at automation.project3ds.oldTest.BrickWidget_OFF1_Test.execute(BrickWidget_OFF1_Test.java:70)
at sun.reflect.GeneratedMethodAccessor89.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- execute -->
  <testcase name="execute" time="21.357" classname="automation.project3ds.oldTest.BrickWidget_OFF1_Test"/>
  <testcase name="execute" time="41.863" classname="automation.project3ds.oldTest.BrickWidget_OFF1_Test"/>
  <testcase name="execute" time="22.847" classname="automation.project3ds.oldTest.BrickWidget_OFF1_Test"/>
  <testcase name="execute" time="39.800" classname="automation.project3ds.oldTest.BrickWidget_OFF1_Test"/>
  <testcase name="execute" time="32.355" classname="automation.project3ds.oldTest.BrickWidget_OFF1_Test">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	[Enrolled] expected [] but found [U]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
[Enrolled] expected [] but found [U]
at automation.project3ds.MySoftAssertAll.assertAll(MySoftAssertAll.java:57)
at automation.project3ds.Action.assertResultV1(Action.java:268)
at automation.project3ds.Action.assertResultV1(Action.java:156)
at automation.project3ds.oldTest.BrickWidget_OFF1_Test.execute(BrickWidget_OFF1_Test.java:70)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- execute -->
  <testcase name="execute" time="44.960" classname="automation.project3ds.oldTest.BrickWidget_OFF1_Test"/>
  <testcase name="execute" time="24.896" classname="automation.project3ds.oldTest.BrickWidget_OFF1_Test"/>
  <testcase name="execute" time="28.500" classname="automation.project3ds.oldTest.BrickWidget_OFF1_Test"/>
  <testcase name="execute" time="52.620" classname="automation.project3ds.oldTest.BrickWidget_OFF1_Test">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	[Enrolled] expected [] but found [U]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
[Enrolled] expected [] but found [U]
at automation.project3ds.MySoftAssertAll.assertAll(MySoftAssertAll.java:57)
at automation.project3ds.Action.assertResultV1(Action.java:268)
at automation.project3ds.Action.assertResultV1(Action.java:156)
at automation.project3ds.oldTest.BrickWidget_OFF1_Test.execute(BrickWidget_OFF1_Test.java:70)
at sun.reflect.GeneratedMethodAccessor89.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- execute -->
  <testcase name="execute" time="22.661" classname="automation.project3ds.oldTest.BrickWidget_OFF1_Test"/>
  <testcase name="execute" time="42.175" classname="automation.project3ds.oldTest.BrickWidget_OFF1_Test"/>
  <testcase name="execute" time="26.138" classname="automation.project3ds.oldTest.BrickWidget_OFF1_Test"/>
  <testcase name="execute" time="39.780" classname="automation.project3ds.oldTest.BrickWidget_OFF1_Test"/>
  <testcase name="execute" time="45.564" classname="automation.project3ds.oldTest.BrickWidget_OFF1_Test"/>
  <testcase name="execute" time="32.257" classname="automation.project3ds.oldTest.BrickWidget_OFF1_Test"/>
  <testcase name="execute" time="39.694" classname="automation.project3ds.oldTest.BrickWidget_OFF1_Test"/>
  <testcase name="execute" time="28.165" classname="automation.project3ds.oldTest.BrickWidget_OFF1_Test"/>
  <testcase name="execute" time="47.692" classname="automation.project3ds.oldTest.BrickWidget_OFF1_Test"/>
  <testcase name="execute" time="30.908" classname="automation.project3ds.oldTest.BrickWidget_OFF1_Test"/>
  <testcase name="execute" time="22.236" classname="automation.project3ds.oldTest.BrickWidget_OFF1_Test"/>
  <testcase name="execute" time="24.248" classname="automation.project3ds.oldTest.BrickWidget_OFF1_Test"/>
</testsuite> <!-- automation.project3ds.oldTest.BrickWidget_OFF1_Test -->
