<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="PW-HAN-063" name="p1.Case13_19_WidgetBrick_1v6_Test_ValidateCardNumber" tests="6" failures="2" timestamp="04 Oct 2019 09:28:12 GMT" time="78.252" errors="0">
  <testcase name="invalidValue" time="10.509" classname="p1.Case13_19_WidgetBrick_1v6_Test_ValidateCardNumber">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	[Card number][ErrorTextValue] expected [Please enter your card number] but found []">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
[Card number][ErrorTextValue] expected [Please enter your card number] but found []
at automation.project3ds.Assertion.end(Assertion.java:26)
at p1.Case13_19_WidgetBrick_1v6_Test_ValidateCardNumber.invalidValue(Case13_19_WidgetBrick_1v6_Test_ValidateCardNumber.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- invalidValue -->
  <testcase name="unsupportedBrand" time="10.732" classname="p1.Case13_19_WidgetBrick_1v6_Test_ValidateCardNumber">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	[Card number][ErrorTextValue] expected [Please enter your card number] but found []">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
[Card number][ErrorTextValue] expected [Please enter your card number] but found []
at automation.project3ds.Assertion.end(Assertion.java:26)
at p1.Case13_19_WidgetBrick_1v6_Test_ValidateCardNumber.unsupportedBrand(Case13_19_WidgetBrick_1v6_Test_ValidateCardNumber.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- unsupportedBrand -->
  <testcase name="supportedBrandButInvalidValue" time="21.357" classname="p1.Case13_19_WidgetBrick_1v6_Test_ValidateCardNumber"/>
  <testcase name="amexCard" time="14.739" classname="p1.Case13_19_WidgetBrick_1v6_Test_ValidateCardNumber"/>
  <testcase name="visaCard" time="10.376" classname="p1.Case13_19_WidgetBrick_1v6_Test_ValidateCardNumber"/>
  <testcase name="masterCard" time="10.539" classname="p1.Case13_19_WidgetBrick_1v6_Test_ValidateCardNumber"/>
</testsuite> <!-- p1.Case13_19_WidgetBrick_1v6_Test_ValidateCardNumber -->
